### ISSUE TITLE
Can't make

### ISSUE THREAD

**Issue by Mochaka** [avtobiff/erlang-uuid#13]
p src/uuid.app.src ebin/uuid.app
erl -make
{"init terminating in do_boot",{undef,[{make,all,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
Makefile:17: recipe for target 'build' failed
make: *** [build] Error 1

Is there something i'm missing?

**Comment by Dania02525** [comment]
I ran into this, and had to edit rebar.config in ChicagoBoss/deps/boss_db to point uuid dependency to github instead of gitorious. Should be:

{uuid,          ".*",   {git, "git://github.com/avtobiff/erlang-uuid.git",           {tag, "9cfe9666f1"}}},

**Comment by avtobiff** [comment]
Fixed in 6df1eaf, released in v0.4.7.

Thanks!
