### ISSUE TITLE
Sed: extra characters at the end of "p" command

### ISSUE THREAD

**Issue by mweibel** [avtobiff/erlang-uuid#3]
`sed: 1: "/vsn/ {s/.*,\s*"\([0-9] ...": extra characters at the end of p command`

when building on OSX

**Comment by METAJIJI** [comment]
Just add `;` symbol before `}`

For example:
```
VERSION   := $(shell sed -n '/vsn/ {s/.*,\s*"\([0-9][0-9.]*\)".*/\1/; p;}' \
```

I'm testing similar code on OS X Maverics.
