### ISSUE TITLE
OS X Mavericks make install fails

### ISSUE THREAD

**Issue by telsgaard** [avtobiff/erlang-uuid#9]
When installing with 'make install' on OSX Mavericks, the install fails due to the appfile version number substitution.

sh-3.2# make install
erl -make
create dist directory and install files
mkdir -p /usr/lib/erlang/lib/uuid-  {vsn, "0.4.4"},/ebin
install -m0644 ebin/\* /usr/lib/erlang/lib/uuid-  {vsn, "0.4.4"},/ebin
install: /usr/lib/erlang/lib/uuid-: Inappropriate file type or format
make: **\* [install] Error 71
sh-3.2#

**Comment by avtobiff** [comment]
Fixed with 446dd9d
